// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  CLOUDFLARE_GQL_TOKEN: string;
  ACCT_ID: string;
  ZONE_ID: string;
  DATE_START: string;
  DATE_END: string;
}
